name: animation_exp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  firebase_auth: ^0.8.4
  flutter_auth_buttons: ^0.3.1  
  flutter_facebook_login: ^2.0.0
  flutter_twitter_login: 
  google_sign_in: ^4.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/img1.jpg
  - assets/img2.jpg
  - assets/img3.jpg
  - assets/img4.jpg
  - assets/img5.jpg
  - assets/avatars/avatar-1.jpg
  - assets/avatars/avatar-2.jpg
  - assets/avatars/avatar-3.jpg
  - assets/avatars/avatar-4.jpg
  - assets/avatars/avatar-5.jpg
  - assets/avatars/avatar-6.jpg
  - assets/findmaxcatchphrase.png
 
  
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Myriad
      fonts:
        - asset: fonts/MYRIADPRO.BOLD-OTF
        - asset: fonts/MYRIADPRO.BOLDCOND-OTF
        - asset: fonts/MYRIADPRO.BOLDCONDIT-OTF
        - asset: fonts/MYRIADPRO.BOLDIT-OTF
        - asset: fonts/MYRIADPRO.COND-OTF
        - asset: fonts/MYRIADPRO.CONDIT-OTF
        - asset: fonts/MyriadPro-Light-OTF
        - asset: fonts/MYRIADPRO.REGULAR-OTF
        - asset: fonts/MYRIADPRO.SEMIBOLD-OTF
        - asset: fonts/MYRIADPRO.SEMIBOLDIT-OTF
        
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
